apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundry-vtt
  namespace: goldengulp
spec:
  accessModes:
  - "ReadWriteOnce"
  storageClassName: "microk8s-hostpath"
  resources:
    requests:
      storage: "10Gi"
