apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: frost-wind-terror

patches:
- patch: |-
    - op: replace
      path: "/apiVersion"
      value: networking.k8s.io/v1
    - op: add
      path: "/spec/rules/0/http/paths/0/pathType"
      value: ImplementationSpecific
    - op: add
      path: "/spec/rules/0/http/paths/0/backend/service"
      value: {}
    - op: add
      path: "/spec/rules/0/http/paths/0/backend/service/port"
      value: {}
    - op: move
      from: "/spec/rules/0/http/paths/0/backend/serviceName"
      path: "/spec/rules/0/http/paths/0/backend/service/name"
    - op: move
      from: "/spec/rules/0/http/paths/0/backend/servicePort"
      path: "/spec/rules/0/http/paths/0/backend/service/port/number"
  target:
    kind: Ingress
    name: oauth2-proxy

resources:
- oauth2-proxy-base.yaml
