apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
          lameduck 5s
        }
        ready
        log . {
          class error
        }
        hosts custom.hosts {
          192.168.1.201 keycloak.mackenzieclark.codes
          192.168.1.201 secrets.mackenzieclark.codes
          192.168.1.201 foundry.goldengulp.com
          192.168.1.201 foundry.frost-wind-terror.group
          fallthrough
        }
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . 8.8.8.8 8.8.4.4
        cache 30
        loop
        reload
        loadbalance
    }
