apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: digitalocean-container-registry
  namespace: tekton-pipelines
spec:
  type: image
  params:
    - name: url
      value: registry.digitalocean.com/nightstone/resume