apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: resume-git
  namespace: tekton-pipelines
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: https://github.com/xmclark/resume