service:
  type: ClusterIP

ingress:
  apiVersion: networking.k8s.io/v1
  enabled: true
  hostname: keycloak.mackenzieclark.codes
  certManager: true
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    certmanager.k8s.io/acme-challenge-type: "dns01"
    certmanager.k8s.io/acme-dns01-provider: "digitalocean"

auth:
  existingSecret: keycloak

rbac:
  create: true

postgresql:
  enabled: true
  existingSecret: keycloak-postgresql

proxyAddressForwarding: true
