apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls-certificate
  namespace: platform
spec:
  secretName: vault-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "secrets.mackenzieclark.codes"
