apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundry-vtt
spec:
  accessModes:
  - "ReadWriteOnce"
  storageClassName: "microk8s-hostpath"
  resources:
    requests:
      storage: "2Gi"
