apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform

patches:
- patch: |-
    - op: replace
      path: "/apiVersion"
      value: rbac.authorization.k8s.io/v1
  target:
    kind: ClusterRole
- patch: |-
    - op: replace
      path: "/apiVersion"
      value: rbac.authorization.k8s.io/v1
  target:
    kind: ClusterRoleBinding
resources:
- datadog-base.yaml
